### PR TITLE
Move library to root of repository

### PR DESCRIPTION
**Pull request by per1234**
A popular library installation technique is to download the library via GitHub's **Clone or download > Download ZIP** and then use the Arduino IDE's **Sketch > Include Library > Add .ZIP Library** on the downloaded file. This requires the library to be in the root of the repository, not in a subfolder. If the library is not in the root of the repository this installation technique fails:
```
Specified folder/zip file does not contain a valid library
```
This is the standard repository structure used in all official Arduino libraries:
https://github.com/arduino-libraries

This move is also required if you wanted to [add your library to the Arduino Library Manager index](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ), which provides an even easier installation option.

### CODE REVIEW

**Comment by bergrans** [comment]
Thanks @per1234 for pointing this out. I have never paid to much attention to the Arduino library standards so thats why it ended up like it is.
Checking out the standards tell me to put the .ccp  and .h files in the **src** folder (not the root) and the documentation in the **extras** folder. Also adding a library.properties file.

**Comment by per1234** [comment]
Putting the source files under the src folder is called the 1.5 Arduino library format. Putting them in the root of the library folder is the 1.0 format. The only downside of the 1.5 format is that it's not compatible with the 1.0.x versions of the Arduino IDE. Since those IDE versions are pretty outdated now I'm not sure it's really so important to maintain backwards compatibility so far back. The 1.0 library format is compatible with the 1.0.x IDE versions as well as the newer IDE versions.

A library.properties file is not required for the 1.0 format but it's still nice to have either way.

There will be no problem not putting the documentation under the extras folder. I wanted to provide the most minimal changes possible in this proposal but I do think it's best to follow the specification.

I'm happy to update this pull request to follow the full 1.5 library format specification if you would like, or if you want to maintain backwards compatibility I can continue with the 1.0 format but still add the library.properties and extras folders. Just let me know what your preference is.

**Comment by bergrans** [comment]
Since the code isn’t compatible with the 1.0 format as it is now there're not much reasons why we should stick to the old format.
Feel free to update your pull request to follow the full 1.5 library format specification. Otherwise I will do it (somewhere in the near feature).  

Best regards,
Martin

**Comment by per1234** [comment]
OK, I have done it.

**Comment by bergrans** [comment]
Thanks @per1234

**Comment by cleveHEX** [comment]
You might also want change versioning to semver.

**Comment by bergrans** [comment]
Good point @CornyjK. Changed the version number and made a new release.
Thanks!

**Pull request merged**
